version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sifra
      POSTGRES_DB: rekboodb
    ports:
      - 5432:5432
    networks:
      - rekboo-net
   
   
  api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=db;Database=rekboodb;Port=5432;User Id=sa;Password=sifra
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9998:9998
    expose:
      - 5184
    depends_on:
      - db
    networks:
      - rekboo-net

  web:
    restart: unless-stopped
    build:
      context: ./rekbooweb
    ports:
      - 9999:9999
    expose:
      - 3000
    networks:
      - rekboo-net
    depends_on:
      - api
   
  nginx:
    image: nginx:latest
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rekboo-net

networks:
  rekboo-net:
    driver: bridge
